### ISSUE TITLE
O endereço para o guia técnico de encomendas mudou

### ISSUE THREAD

**Issue by rafaelol** [garu/WWW-Correios-SRO#9]
O link no comentário está quebrado - https://github.com/garu/WWW-Correios-SRO/blob/master/lib/WWW/Correios/SRO.pm#L228

O novo link é esse: http://www.correios.com.br/para-sua-empresa/servicos-para-o-seu-contrato/guias/enderecamento/arquivos/guia_tecnico_encomendas.pdf/at_download/file

**Comment by leobetosouza** [comment]
resolved in 57b7b1743874f23280a0f993ec55fe2c4798767d

**Comment by garu** [comment]
<3

**Comment by garu** [comment]
@rafaelol @leobetosouza qual dos dois vai fazer o novo release pro cpan? :)

**Comment by garu** [comment]
Vou ajudar, caso vcs não se lembrem como :P

1. incrementar o `$VERSION` em `lib/WWW/Correios/SRO.pm`
2. adicionar as mudanças no arquivo `Changes`
3. make dist && make disttest (isso deve criar o .tar.gz)
4. `cpan-upload $nome_do_tar_gz` (cpanm [CPAN::Uploader](https://metacpan.org/pod/distribution/CPAN-Uploader/bin/cpan-upload) se não tiverem instalado)

**Comment by rafaelol** [comment]
Faça as honras, beto. Você quem lançou o commit. :)
Em 16 de dez de 2015 11:32 PM, "Breno G. de Oliveira" <
notifications@github.com> escreveu:

**Comment by leobetosouza** [comment]
Amanhã eu faço. Tô na fila do cinema :)

**Comment by rafaelol** [comment]
Já tô na cadeira esperando começar a sessão. :)
Em 16 de dez de 2015 11:36 PM, "Leonardo Alberto Souza" <
notifications@github.com> escreveu:
